#!/bin/bash

echo "🚀 Plane Project Scripts Help"
echo "================================"
echo ""
echo "📋 Available Scripts:"
echo ""
echo "🏃‍♂️ Core Management:"
echo "  ./start-plane.sh          - Start all services"
echo "  ./stop-plane.sh           - Stop all services"
echo "  ./scripts/restart-plane.sh    - Restart all services"
echo "  ./scripts/rebuild-plane.sh    - Rebuild and start all services"
echo ""
echo "🔄 Service-Specific:"
echo "  ./scripts/restart-api.sh      - Restart API service only"
echo "  ./scripts/restart-web.sh      - Restart Web service only"
echo "  ./scripts/restart-frontend.sh - Restart all frontend services"
echo ""
echo "🗄️ Database:"
echo "  ./scripts/migrate-db.sh       - Run database migrations"
echo "  ./scripts/db-shell.sh         - Open database shell"
echo ""
echo "👤 User Management:"
echo "  ./scripts/create-admin.sh     - Create admin user"
echo ""
echo "🔧 Development:"
echo "  ./scripts/api-shell.sh        - Open Django shell"
echo "  ./scripts/logs.sh             - View service logs"
echo "  ./scripts/status.sh           - Check project status"
echo "  ./scripts/clean.sh            - Clean up containers"
echo ""
echo "📖 Documentation:"
echo "  cat scripts/README.md         - Full documentation"
echo ""
echo "🌐 Service URLs:"
echo "  Web App: http://localhost:3000"
echo "  Admin Panel: http://localhost:3001"
echo "  Space App: http://localhost:3002"
echo "  API: http://localhost:8000"
echo ""
echo "💡 Quick Start:"
echo "  ./start-plane.sh              - Start the project"
echo "  ./scripts/status.sh           - Check if running"
echo "  ./scripts/logs.sh             - View logs"
echo ""
echo "================================"
