# Generated by Django 4.2.22 on 2025-09-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0100_profile_has_marketing_email_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', help_text='User role for system-wide permissions', max_length=20),
        ),
    ]
