# Generated by Django 4.2.7 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0101_add_user_role_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('slug', models.SlugField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Maximum number of users allowed in this company', verbose_name='Maximum Users')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='Company Logo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Primary Color')),
                ('logo_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='db.fileasset')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_companies', to='db.user', verbose_name='Company Manager')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('guest', 'Guest')], default='staff', max_length=20, verbose_name='Role in Company')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('company_display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Display Name in Company')),
                ('company_role_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title in Company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='db.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to='db.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'db_table': 'company_users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='primary_company',
            field=models.ForeignKey(blank=True, help_text='Primary company this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_company_users', to='db.company'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='company_unique_slug_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='companyuser',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'user'), name='company_user_unique_company_user_when_deleted_at_null'),
        ),
    ]

